version: "3.9"

services:
  redis:
    hostname: redis
    image: redis:6-alpine
    networks: [walletconnect-monorepo]
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    networks: [walletconnect-monorepo]
    ports:
      - 8080:80
    depends_on:
      relay:
        condition: service_healthy
  relay:
    hostname: relay
    deploy:
      replicas: 4
    networks: [walletconnect-monorepo]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=TRACE
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis:
  node_modules:

networks:
  walletconnect-monorepo:
    driver: bridge
